-- begin PROPOSALS_INSTRUMENT
create unique index IDX_PROPOSALS_INSTRUMENT_UNIQ_NAME on PROPOSALS_INSTRUMENT (NAME)^
-- end PROPOSALS_INSTRUMENT
-- begin PROPOSALS_PROPOSAL
alter table PROPOSALS_PROPOSAL add constraint FK_PROPOSALS_PROPOSAL_ON_INSTRUMENT foreign key (INSTRUMENT_ID) references PROPOSALS_INSTRUMENT(ID)^
alter table PROPOSALS_PROPOSAL add constraint FK_PROPOSALS_PROPOSAL_ON_APPLICANT foreign key (APPLICANT_ID) references SEC_USER(ID)^
alter table PROPOSALS_PROPOSAL add constraint FK_PROPOSALS_PROPOSAL_ON_DELEGATE foreign key (DELEGATE_ID) references SEC_USER(ID)^
alter table PROPOSALS_PROPOSAL add constraint FK_PROPOSALS_PROPOSAL_ON_RESPONSIBLE foreign key (RESPONSIBLE_ID) references SEC_ROLE(ID)^
create index IDX_PROPOSALS_PROPOSAL_ON_INSTRUMENT on PROPOSALS_PROPOSAL (INSTRUMENT_ID)^
create index IDX_PROPOSALS_PROPOSAL_ON_APPLICANT on PROPOSALS_PROPOSAL (APPLICANT_ID)^
create index IDX_PROPOSALS_PROPOSAL_ON_DELEGATE on PROPOSALS_PROPOSAL (DELEGATE_ID)^
create index IDX_PROPOSALS_PROPOSAL_ON_RESPONSIBLE on PROPOSALS_PROPOSAL (RESPONSIBLE_ID)^
-- end PROPOSALS_PROPOSAL
